### ISSUE TITLE
Brush shader mismatch

### ISSUE THREAD

**Issue by rawnsley** [icosa-foundation/three-icosa#3]
The shaders in this repository ([example](https://github.com/icosa-foundation/three-icosa/blob/ebb3a1e11ed93180217bfa732e98aafcba569d88/brushes/DoubleTaperedMarker-0d3889f3-3ede-470c-8af4-de4813306126/DoubleTaperedMarker-0d3889f3-3ede-470c-8af4-de4813306126-v10.0-fragment.glsl)) don't match the ones on the hosted server ([example](https://icosa-foundation.github.io/icosa-sketch-assets/brushes/DoubleTaperedMarker-0d3889f3-3ede-470c-8af4-de4813306126/DoubleTaperedMarker-0d3889f3-3ede-470c-8af4-de4813306126-v10.0-vertex.glsl)).

Fatally, the ones in this repository start with `#version 300 es`, which stops them compiling in threejs ([similar issue](https://github.com/mrdoob/three.js/issues/26532)).

There may be other differences, but removing this line appears to work at least. Perhaps this repository is out of sync with the hosted version?

**Comment by mikeskydev** [comment]
You're correct that they're out of sync - the hosted ones were fixed during development debugging, but not updated here, sorry about that.

The issue you linked should be the correct change, as reflected in the hosted version. Honestly I'm not sure why three.js decided to move that version tag out of the shaders, as it worked perfectly fine before on older revisions.

**Comment by andybak** [comment]
Fixed in f930c7 (I still need to do an npm release)

@rawnsley out of curiosity - what are you doing that triggered this bug? I presume you're not using https://icosa-foundation.github.io/gallery-viewer/

**Comment by rawnsley** [comment]
@mikeskydev @andybak Thanks for the super quick response.

I'm integrating it into our platform and it was running fine with the foundation hosted links (with CORS disabled), but failed when I tried to host the brushes on my own server for production, which led me to try the index.html demo page using the local brushes (again with browser security disabled).
